<?php

namespace Database\Seeders;

use App\Models\Business;
use Illuminate\Database\Seeder;

class BusinessSeeder extends Seeder
{
    /**
     * Seed the business table with production reference data.
     */
    public function run(): void
    {
        $businesses = [
            [
                'id' => '9c99b924-ac5d-4038-9f54-8ff59ee1230d',
                'business_type' => 1,
                'business_tax_no' => '0105558192509',
                'business_vat_status' => 1,
                'business_vat_file' => 'vatDocument-20240521161802-1721888818.jpg',
                'business_code' => 'ABI',
                'business_name' => 'บริษัท เอบี อินโนเวชั่นส์ จำกัด',
                'business_address1' => '133 ถนนกาญจนาภิเษก',
                'business_address2' => 'แขวง แสมดำ เขต บางขุนเทียน กทม. 10150',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 1,
                'business_name_en' => 'AB Innovations Co., Ltd.',
                'business_address1_en' => '133 Kanchanaphisek Road, Saemdam Subdistrict',
                'business_address2_en' => 'Bang Khun Thian District, Bangkok 10150',
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 12,
                'business_business_finance_year' => 12,
                'business_tel' => '024577217',
                'business_phone' => '0638355725',
                'business_fax' => null,
                'business_website' => 'www.abgroup.co.th',
                'business_logo' => 'logoCompany-20240521161802-1721840501.png',
                'business_stamp' => 'โลโก้ขาวดำ-1723696466.jpg',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 10:01:41',
                'updated_at' => '2026-03-11 02:36:17',
                'sales_target_amount' => 10000000.00,
            ],
            [
                'id' => '9c9aaeae-9949-4851-9225-ca2f1eb6eef3',
                'business_type' => 1,
                'business_tax_no' => '0105550108096',
                'business_vat_status' => 1,
                'business_vat_file' => 'vatDocument-20240521164750-1721888787.pdf',
                'business_code' => 'SU',
                'business_name' => 'บริษัท สปีดยูเนี่ยน (ประเทศไทย) จำกัด',
                'business_address1' => '133 ถนนกาญจนาภิเษก',
                'business_address2' => 'แสมดำ เขตบางขุนเทียน กรุงเทพมหานคร 10150',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 1,
                'business_name_en' => 'Speed Union (Thailand) Co., Ltd.',
                'business_address1_en' => '133 Kanchanaphisek Road, Saemdam Subdistrict',
                'business_address2_en' => 'Bang Khun Thian District, Bangkok 10150',
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 12,
                'business_business_finance_year' => 12,
                'business_tel' => '024577217',
                'business_phone' => '0638355725',
                'business_fax' => null,
                'business_website' => 'www.speedunion.co',
                'business_logo' => '202406 Expenes SU-1721881695.png',
                'business_stamp' => 'rubberStamp-20240521164750-1721881695.jpg',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 21:28:15',
                'updated_at' => '2024-07-24 23:26:27',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => '9c9aaf30-efe0-44ca-a9b8-efb984eed8e3',
                'business_type' => 1,
                'business_tax_no' => '0105565089149',
                'business_vat_status' => 1,
                'business_vat_file' => 'vatDocument-20240521165157-1721888839.pdf',
                'business_code' => 'ABT',
                'business_name' => 'บริษัท เอบี เทคโนโลยี จำกัด',
                'business_address1' => '133 ถนนกาญจนาภิเษก',
                'business_address2' => 'แขวงแสมดำ เขตบางขุนเทียน กรุงเทพมหานคร 10150',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 1,
                'business_name_en' => 'AB Technology Co., Ltd.',
                'business_address1_en' => '133 Kanchanaphisek Road',
                'business_address2_en' => 'Samdam, Bangkhuntian, Bangkok 10150',
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 12,
                'business_business_finance_year' => 12,
                'business_tel' => '024577217',
                'business_phone' => '0638355725',
                'business_fax' => null,
                'business_website' => 'www.abgroup.co.th',
                'business_logo' => 'logoCompany-20240521165157-1721881781.png',
                'business_stamp' => 'rubberStamp-20240521165157-1721881781.jpg',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 21:29:41',
                'updated_at' => '2024-07-24 23:27:19',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => '9c9aafbc-f74a-4e30-b44a-1209b30431ad',
                'business_type' => 1,
                'business_tax_no' => '0100000000000',
                'business_vat_status' => 1,
                'business_vat_file' => null,
                'business_code' => 'ABBL',
                'business_name' => 'ABBL Automation Co-Work',
                'business_address1' => 'Bangkok',
                'business_address2' => null,
                'business_branch_status' => 1,
                'business_branch_no' => 0,
                'business_branch_name' => 'สำนักงานใหญ่',
                'business_en_status' => 1,
                'business_name_en' => 'ABBL Automation Co-Work',
                'business_address1_en' => 'Bangkok',
                'business_address2_en' => null,
                'business_branch_no_en' => 0,
                'business_branch_name_en' => 'Head Office',
                'business_account_finance_year' => 12,
                'business_business_finance_year' => 12,
                'business_tel' => '020000000',
                'business_phone' => '020000000',
                'business_fax' => null,
                'business_website' => null,
                'business_logo' => null,
                'business_stamp' => null,
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => true,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 21:31:12',
                'updated_at' => '2026-07-09 20:38:25',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => '9c9ab022-f4a7-4d5e-bc41-c48769106730',
                'business_type' => 1,
                'business_tax_no' => '0105560111669',
                'business_vat_status' => 1,
                'business_vat_file' => 'vatDocument-20240617083127-1721888888.pdf',
                'business_code' => 'HFT',
                'business_name' => 'บริษัท แฮปปี้ฟาร์มส์ (ประเทศไทย) จำกัด',
                'business_address1' => '469 ถนนเเพชรเกษม',
                'business_address2' => 'บางหว้า เขตภาษีเจริญ กรุงเทพมหานคร 10160',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 1,
                'business_name_en' => 'Happy Farms (Thailand) Ltd',
                'business_address1_en' => '469 Phetkasem Rd',
                'business_address2_en' => 'Bang Wa, Khet Phasi Charoen, Bangkok 10160',
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 6,
                'business_business_finance_year' => 6,
                'business_tel' => '024577217',
                'business_phone' => '0849939113',
                'business_fax' => null,
                'business_website' => 'www.gerandthailand.com',
                'business_logo' => null,
                'business_stamp' => 'Screenshot-2025-02-07-214752-1738939700.png',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 21:32:19',
                'updated_at' => '2025-02-07 14:48:20',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => '9c9ab06b-0e9a-4dc6-971d-80481d32ff86',
                'business_type' => 3,
                'business_tax_no' => null,
                'business_vat_status' => 1,
                'business_vat_file' => null,
                'business_code' => 'TRI',
                'business_name' => 'นายธวัชชัย อัฐปัน และนายพัชร์พล พชรวรณวิชญ์ และนายอชิตศักดิ์ พชรวรณวิชญ์',
                'business_address1' => null,
                'business_address2' => null,
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 0,
                'business_name_en' => null,
                'business_address1_en' => null,
                'business_address2_en' => null,
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 1,
                'business_business_finance_year' => 1,
                'business_tel' => null,
                'business_phone' => '0849939113',
                'business_fax' => null,
                'business_website' => null,
                'business_logo' => null,
                'business_stamp' => null,
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 0,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2024-07-24 21:33:07',
                'updated_at' => '2025-07-02 07:43:58',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => '9f75614e-14fd-4d37-913e-cb0e01581cbd',
                'business_type' => 1,
                'business_tax_no' => '0105550108096',
                'business_vat_status' => 1,
                'business_vat_file' => '127076_0-1753264924.jpg',
                'business_code' => 'ABLM',
                'business_name' => 'บริษัท เอบี ลอนดรี้ แมชชีนเนอรี่ จำกัด',
                'business_address1' => '133 ถ.กาญจนาภิเษก',
                'business_address2' => 'แสมดำ เขตบางขุนเทียน กรุงเทพมหานคร 10150',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 1,
                'business_name_en' => 'AB LAUNDRY MACHINERY',
                'business_address1_en' => '133 Kanchanaphisek rd.,',
                'business_address2_en' => 'Samae Dam, Khet Bang Khun Thian, Bangkok, 10150',
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 6,
                'business_business_finance_year' => 12,
                'business_tel' => '024577217',
                'business_phone' => '0918366579',
                'business_fax' => null,
                'business_website' => 'www.ablm.co.th',
                'business_logo' => 'ABLM-1753264924.png',
                'business_stamp' => 'ตร-ปร-ท-บ-ABLM-1777520308.png',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2025-07-23 10:02:04',
                'updated_at' => '2026-04-30 03:38:28',
                'sales_target_amount' => 1000000.00,
            ],
            [
                'id' => 'a09918b6-7719-407a-943e-b3b1aedeb453',
                'business_type' => 1,
                'business_tax_no' => '0105558192509',
                'business_vat_status' => 1,
                'business_vat_file' => 'PP20_ABI-133-1765794050.pdf',
                'business_code' => 'ABBN',
                'business_name' => 'บริษัท เอบี อินโนเวชั่นส์ จำกัด',
                'business_address1' => '133 ถนนกาญจนาภิเษก',
                'business_address2' => 'แขวงบางหว้า เขตภาษีเจริญ กทม. 10150',
                'business_branch_status' => 0,
                'business_branch_no' => null,
                'business_branch_name' => null,
                'business_en_status' => 0,
                'business_name_en' => null,
                'business_address1_en' => null,
                'business_address2_en' => null,
                'business_branch_no_en' => null,
                'business_branch_name_en' => null,
                'business_account_finance_year' => 6,
                'business_business_finance_year' => 12,
                'business_tel' => '026628558',
                'business_phone' => '',
                'business_fax' => null,
                'business_website' => 'www.browywash.com',
                'business_logo' => 'AB-Group-Innovations-logo_0_0-1765794050.png',
                'business_stamp' => 'AB-Group-Innovations-logo_0_0-1765794050.png',
                'attach_qt' => null,
                'attach_qt_en' => null,
                'attach_po' => null,
                'attach_po_en' => null,
                'business_status' => 1,
                'allow_issue' => false,
                'business_payment_date' => null,
                'business_payment_day' => null,
                'business_payment_month' => null,
                'created_at' => '2025-12-15 10:20:50',
                'updated_at' => '2025-12-15 10:34:53',
                'sales_target_amount' => 0.00,
            ],
        ];

        Business::unguarded(function () use ($businesses) {
            foreach ($businesses as $business) {
                Business::updateOrCreate(
                    ['id' => $business['id']],
                    $business
                );
            }
        });
    }
}
